---
- name: checking the status
  hosts: 192.168.0.138
  remote_user: root
  tasks:
    - name: checking the status
      script: /var/lib/awx/projects/ansible/system.yaml
#      command : echo "systemctl status {{ item }}" 
      register: All_service_status
    - name: showing report
      debug:
        var: All_service_status
