---
- name: checking the status
  hosts: localhost
  remote_user: root
  tasks:
    - name: checking the status
      shell: /root/system.sh
#      command : echo "systemctl status {{ item }}" 
      register: All_service_status
    - name: showing report
      debug:
        var: All_service_status.stdout_lines
