---
- name: checking the status
  hosts: 192.168.0.138
  remote_user: root
  tasks:
    - name: checking the status
      shell: systemctl status "{{ item }}"
#      command : echo "systemctl status {{ item }}" 
      loop:
        - automation-controller
        - nginx
        - redis
        - postgresql
        - supervisord
        - receptor
      register: All_service_status
    - name: showing report
      debug:
        var: All_service_status
