---
- name: checking the status
  hosts: localhost
  tasks:
    - name: checking the status
      service:
        - name: "{{item}}"
          state: status
      loop:
        - automation-controller
        - postgresql
        - redis
        - nginx
        - supervisord
        - receptor
      register: All_service_status
      ignore_errors: yes
    - name: showing report
      debug:
        var: All_service_status
