- hosts: localhost
  name: List the contents of home directory

  tasks:
          - name: List files and folder in home directory
            shell: ls -l 
            register: command_output

          - debug:
                   var: command_output.stdout_lines
